.TH DMENU\-DRAG\-AND\-DROP 1 dmenu\-drag\-and\-drop
.SH NAME
dmenu\-drag\-and\-drop \- dmenu drag and drop \- select files to drag and drop with dmenu
.SH SYNOPSIS
.B dmenu\-drag\-and\-drop
[path]
.SH DESCRIPTION
.B dmenu\-drag\-and\-drop
when called will repeatively call dmenu-file with its one and only argument being passed off to dmenu-file the first time around. It will continue to do so until the escape key is pressed. Then all the files that have been selected will be passed of to dragon\-drag\-and\-drop to be draged and dropped collectively into a program.
.SH AUTHORS
Written by Zachary Schlitt <ztschlitt@gmail.com>
.SH LICENSE
MIT
.SH SEE ALSO
.BR dmenu (1),
.BR dragon\-drag\-and\-drop (1),
.BR dmenu-file (1)
